### ISSUE TITLE
support for color glyphs

### ISSUE THREAD

**Issue by ks32** [Tehreer/Tehreer-Android#21]
It should support color glyphs. CPAL/COLR opentype tables. Best solution will be to use harfbuzz for rendering.

**Comment by mta452** [comment]
Can you please make a fork of the project with harfbuzz support? I believe only JNI methods of 'ShapingEngine' and 'ShapingResult' would need to be implemented.
I'll take a look at the 'CPAL' and 'COLR' tables and find out ways to support these. If you have a font that contains these tables, please share that as well for testing purposes.

**Comment by ks32** [comment]
here is the color font link:
https://www.amirifont.org/AmiriQuranColored.otf
https://www.amirifont.org/fatiha-colored.html

**Comment by mta452** [comment]
I have added experimental support for color glyphs in `dev_color` branch. Let me know your review.

**Comment by mta452** [comment]
The support color glyphs has been added in `v2.5`
